server:
   port: 8090

spring:
   application:
      name: airport-service
   datasource:
      url: jdbc:mysql://smoothstack-project.cqxybfmjssty.us-east-2.rds.amazonaws.com:3306/utopia
      username: ${SPRING_DB_UNAME}
      password: ${SPRING_DB_PASS}
      hikari:
         maximum-pool-size: 3
      
#spring:
#   datasource:
#      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/utopia
#      username: root
#      password: eb9TcK9Rfx!#
      
   jpa:
      hibernate:
         naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      open-in-view: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
